# raffle.rb
# Summary: quick-and-dirty Ruby script to raffle a prize.
# Author: Kevin Noonan.
#
# State in advance: attendance at the event is mandatory to be 
# eligible for the prize-draw.
# If someone who's not attending is randomly chosen, re-run the script.
#
# (The list below has *all* Ruby Ireland members, at least on Meetup
# as at 15th April 2013.)
#
# Some people only use first-names on Meetup. 
# Refer to the Meetup profile if you can't distinguish who should win.

members= [ 
"cathal Browne",
"Adam McCarthy",
"Adrien Siami",
"Aidan Finn",
"Aidan Haran",
"Alan",
"Alan Larkin",
"Alex Beregszaszi",
"Alexander Nordlund",
"Anatoly Mikhaylov",
"Andrei Balcanasu",
"Andrej Hosna",
"Aoife",
"Artur",
"Barry Byrne",
"Barry Kirby",
"Bob Long",
"Brian Kenny",
"Brian Phillips",
"Brian Ward",
"Cathal Browne",
"Charlie",
"Chris McGrath",
"Chris Mowforth",
"Chris Xatzi",
"Christian Sommerauer",
"Ciaran Lee",
"Ciaran Archer",
"Clive Foley",
"Colm Larkin",
"Colum Twomey",
"Conor Nugent",
"cormac",
"Cormac Kelly",
"Dan Laffan",
"Dani Martos Kst",
"Daniel Beere",
"Darragh Curran",
"David Curran",
"David Ramalho",
"Declan",
"Des McDonnell",
"Diarmuid Bourke",
"ed lenox",
"Elaine",
"Emily",
"Emmanuel Bourgerie",
"Eoin",
"Eric Theise",
"Ewa",
"Fergal Condron",
"Fergal R",
"Fernando Abellan",
"Finbarr O'Donoghue",
"Fintan Fairmichael",
"Garrett Heaver",
"Gary R",
"Gavin Joyce",
"Ger Hartnett",
"Ger Kelly",
"gian",
"Gosia",
"Greg",
"Greg Porter",
"Gregor Macadam",
"Gregory Chomatas",
"gstenson",
"Iain McNulty",
"Isma",
"Ivano",
"Jakub Jarosz",
"James Hogan",
"Jan Blanchard",
"Janelle Eagleton",
"Jaume Tarradas Llort",
"Jena",
"Jimmy Tang",
"John Bradley",
"John Coleman",
"John Costello",
"John Kavanagh",
"John O'Gara",
"John Smyth",
"Jos",
"Jules",
"Julien Hugon",
"Juliusz",
"Karl Grogan",
"Kate",
"Kevin Fagan",
"Kevin Noonan",
"Leigh Moyle",
"Liam Tyrrell",
"Luca Spiller",
"Marco",
"Marco Campana",
"Mark Finlay",
"Mark Gomba",
"Mark Gray",
"Mark Howard",
"Mark King",
"Mark King",
"Mark Sullivan",
"Michael Walsh",
"Mike Gilbert",
"Miles McGuire",
"Milton Amaral",
"Monir",
"Myriam",
"Neil Burns",
"Niall Murphy",
"Nucc",
"Oisin Hurley",
"Orla",
"Paolo Dona",
"Patrick Kiernan",
"Paul Mc Carthy",
"Paul Michael Watson",
"Paul O'Connor",
"Paul Williams",
"Pawel Raszewski",
"Peter McKenna",
"Peter Wood",
"Petra",
"Phil",
"Pierre Schambacher",
"Piotr Usewicz",
"pradeep",
"Rachel Burke",
"Rinaldo",
"Robert Clancy",
"Robert Shedd",
"Ross Shannon",
"Sajeev Zacharias",
"Sarah",
"Sarah Gavra Boland",
"Shane Grimes",
"Shane Moore",
"Simon Rand",
"Stefan Mitchell",
"Stephen Flinter",
"Stephen Roantree",
"Steve Quinlan",
"Suzy Fynes",
"Sebastien Le Callonnec",
"Thilo",
"tim geaney",
"Tom Van Eyck",
"Tony Cronin",
"Veronica Kelly",
"Victor",
"Vinny Glennon",
"Wal",
"Wesley Gorman",
"Wisam Fadel",
"Zoltan Debre"
]

size=members.length

print "number of members: "
puts size

random_choice=rand(size).to_i

puts members[random_choice]
